version: "3.4"
services:
  frontend:
    image: kotsur/otus-public-lesson-front:latest
    environment:
      VITE_SERVER_URL: backend
    ports:
      - "8092:80"
    depends_on:
      - backend

  backend:
    image: kotsur/otus-public-lesson-api:latest
    environment:
      JWT_ACCESS_SECRET: secret
      JWT_REFRESH_SECRET: secret
      JWT_ACCESS_EXPIRES_SEC: 600
      JWT_REFRESH_EXPIRES_SEC: 600000
      POSTGRES_URL: jdbc:postgresql://postgres/otus-coin-market
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SMS_PROVIDER_URL: http://192.168.1.81:8090/sms/send
    ports:
      - "8091:8080"
    depends_on:
      - postgres
    links:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:6.2.4
    container_name: redis-otus-coin-market
    command:
      - "redis-server"
      - '--save ""'
      - "--appendonly no"
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres-otus-coin-market
    restart: on-failure
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: otus-coin-market
    ports:
      - "5433:5432"
    healthcheck:
      test:
        - CMD
        - psql
        - "-U"
        - postgres
        - "-c"
        - SELECT 1
      interval: 10s
      timeout: 2s
      retries: 6
